### ISSUE TITLE
Error when trying to Clone via visual studio, Even .zip extraction also was not successful after download

### ISSUE THREAD

**Issue by HydTechie** [evolutionary-architecture/evolutionary-architecture-by-example#132]
**1.Error when trying to Clone via visual studio, 
2.Even after download,  .zip extraction also was not successful after download**
![image](https://github.com/evolutionary-architecture/evolutionary-architecture-by-example/assets/4332559/e3f17af6-e672-41b8-8fe6-8d4f74c52b96)

**Comment by kamilbaczek** [comment]
Hello @HydTechie, I don't have windows, but i will check on my brother computer today. Thanks for reporting this.

**Comment by kamilbaczek** [comment]
Hello @HydTechie  👋,

You cannot download the repo because we have files with long paths. Could you change your computer's Git path limit as shown in this video? 📹

Thanks! 😊

 https://www.youtube.com/watch?v=aNpy9r9wkE0
