### ISSUE TITLE
Broken links in Chapter 1 readme

### ISSUE THREAD

**Issue by Freizeithose** [evolutionary-architecture/evolutionary-architecture-by-example#37]
**Description**
[Chapter-1-initial-architecture/README.adoc](https://github.com/evolutionary-architecture/evolutionary-architecture-by-example/blob/main/Chapter-1-initial-architecture/README.adoc) contains two broken links to code in this repository.

For example:
>You can check how does it look like [here](https://github.com/meaboutsoftware/evolutionary-architecture/tree/main/Chapter-1-initial-architecture/Src/Fitnet/Contracts/SignContract).

**Solution**
In the links path `meaboutsoftware/evolutionary-architecture` needs to re replaced with `evolutionary-architecture/evolutionary-architecture-by-example`

**Comment by meaboutsoftware** [comment]
Resolved with https://github.com/evolutionary-architecture/evolutionary-architecture-by-example/pull/38
