### ISSUE TITLE
Docker file for chapter 1 references dotnet 7 rather that dotnet 8

### ISSUE THREAD

**Issue by gslam2k** [evolutionary-architecture/evolutionary-architecture-by-example#91]
**Describe the bug**
Docker file for chapter 1 references dotnet 7 rather that dotnet 8

**To Reproduce**
1. run docker-compose build in chapter 1 src directory

**Expected behavior**
Builds without issue.

**Screenshots**

**Desktop (please complete the following information):**
 -Windows 11

**Smartphone (please complete the following information):**
 - N/A
 - 
**Additional context**
N/A.

**Comment by kamilbaczek** [comment]
Hi @gslam2k. Thanks for this issue. We will fix it shortly.
